### ISSUE TITLE
Support for animated stickers

### ISSUE THREAD

**Issue by CrackerKSR** [AkramChauhan/WhatsApp-Stickers-using-Flutter#2]
HI, How to enable the animated stickers support. I read the official repo code changes for animated sicker support. then added boolean key for animated sticker. But could not get success with that. please update this repo for animated stickers or give hint how to implement it

**Comment by AkramChauhan** [comment]
We supports animated stickers now.
Check implementation by @jigneshpanda here https://github.com/jigneshpandav/whatsapp_stickers_handler
