### ISSUE TITLE
Please Upgrade This Package not Working with Latest Flutter Version

### ISSUE THREAD

**Issue by hanumanjiblog** [AkramChauhan/WhatsApp-Stickers-using-Flutter#3]
Please Upgrade This Package not Working with Latest Flutter Version

**Comment by jigneshpandav** [comment]
Hello
Have just created new project and resolved issues 
you can check here https://github.com/jigneshpandav/whatsapp_stickers_handler

**Comment by AkramChauhan** [comment]
Thank you @jigneshpandav 
Implemeneted changes. Now using your plugin :)
